
SELECT *
FROM [gun violence].[gun violence].dbo.[cleaned_mass_shootings_2014-2023];


 /* STATISTICS FOR MONTHS - AVG VICTIMS, TOTAL VICTIMS, NUM OF INCIDENTS IN A MONTH */
SELECT DISTINCT CMS1.Month AS MONTH,
		ROUND((SELECT AVG(CAST(Total_Victims AS float))
		FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023] CMS2
		WHERE CMS2.Month = CMS1.Month), 2) AS MONTH_AVG,
		(SELECT SUM(Total_Victims)
		FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023] CMS2
		WHERE CMS2.Month = CMS1.Month) AS MONTH_TOTAL_VICTIMS,
		(SELECT COUNT(*)
		FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023] CMS2
		WHERE CMS2.Month = CMS1.Month) AS MONTH_NUM_INCIDENTS
FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023] CMS1
ORDER BY CMS1.Month;

SELECT SUM(Victims_Killed)
FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023];

/* STATISTICS FOR TOTAL NUMBER OF INCIDENTS */
SELECT DISTINCT CMS.US_REGION,
		(SELECT COUNT(*) FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023] WHERE US_Region = CMS.US_REGION),
		(SELECT COUNT(*) FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023]) AS TOTAL,
		ROUND(CAST((SELECT COUNT(*) FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023] WHERE US_Region = CMS.US_REGION) AS FLOAT)/(SELECT COUNT(*) FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023]) * 100, 2)  AS PERCENTAGE
FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023] CMS
GROUP BY CMS.US_REGION;

/* STATISTICS FOR TOTAL VICTIMS */
SELECT DISTINCT CMS.US_REGION,
		(SELECT SUM(TOTAL_VICTIMS) FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023] WHERE US_Region = CMS.US_REGION),
		(SELECT SUM(TOTAL_VICTIMS) FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023]) AS TOTAL,
		ROUND(CAST((SELECT SUM(TOTAL_VICTIMS) FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023] WHERE US_Region = CMS.US_REGION) AS FLOAT)/(SELECT SUM(TOTAL_VICTIMS) FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023]) * 100, 2)  AS PERCENTAGE
FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023] CMS
GROUP BY CMS.US_REGION;

/* STATISTICS FOR VICTIMS INJURED */
SELECT DISTINCT CMS.US_REGION,
		(SELECT SUM(Victims_Injured) FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023] WHERE US_Region = CMS.US_REGION),
		(SELECT SUM(Victims_Injured) FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023]) AS TOTAL,
		ROUND(CAST((SELECT SUM(Victims_Injured) FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023] WHERE US_Region = CMS.US_REGION) AS FLOAT)/(SELECT SUM(Victims_Injured) FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023]) * 100, 2)  AS PERCENTAGE
FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023] CMS
GROUP BY CMS.US_REGION;

/* STATISTICS FOR VICTIMS KILLED */
SELECT DISTINCT CMS.US_REGION,
		(SELECT SUM(Victims_Killed) FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023] WHERE US_Region = CMS.US_REGION),
		(SELECT SUM(Victims_Killed) FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023]) AS TOTAL,
		ROUND(CAST((SELECT SUM(Victims_Killed) FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023] WHERE US_Region = CMS.US_REGION) AS FLOAT)/(SELECT SUM(Victims_Killed) FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023]) * 100, 2)  AS PERCENTAGE
FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023] CMS
GROUP BY CMS.US_REGION;

/* STATE STATISTICS - NUMBER OF INCIDENTS */
SELECT STATE_NAME,
		US_REGION,
		COUNT(*) AS NUM_INCIDENTS,
		SUM(TOTAL_VICTIMS) AS TOTAL_VICTIMS,
		SUM(VICTIMS_KILLED) AS VICTIMS_KILLED,
		SUM(VICTIMS_INJURED) AS VICTIMS_INJURED
FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023]
GROUP BY State_Name, US_Region
ORDER BY NUM_INCIDENTS DESC;

/* GET TOP POPULATED STATES (ON AVERAGE) */
SELECT NAME,
		(POPESTIMATE2014 + POPESTIMATE2015 + POPESTIMATE2016 + POPESTIMATE2017 + POPESTIMATE2018 + POPESTIMATE2019 + POPESTIMATE2020 + POPESTIMATE2021 + POPESTIMATE2022 + POPESTIMATE2023) / 10 AS AVG_POPULATION
FROM [state population].dbo.cleaned_nst_est_2014_2023
WHERE NAME NOT IN ('United States', 'South Region', 'West Region', 'Midwest Region', 'Northeast Region')
ORDER BY POPESTIMATE2023 DESC;

/* CITY - calculating incident rate */
WITH CONSOLIDATED AS (
	SELECT NAME,
			STNAME,
			AVG(POPESTIMATE2014) AS POPESTIMATE2014,
			AVG(POPESTIMATE2015) AS POPESTIMATE2015,
			AVG(POPESTIMATE2016) AS POPESTIMATE2016,
			AVG(POPESTIMATE2017) AS POPESTIMATE2017,
			AVG(POPESTIMATE2018) AS POPESTIMATE2018,
			AVG(POPESTIMATE2019) AS POPESTIMATE2019,
			AVG(POPESTIMATE2020) AS POPESTIMATE2020,
			AVG(POPESTIMATE2021) AS POPESTIMATE2021,
			AVG(POPESTIMATE2022) AS POPESTIMATE2022,
			AVG(POPESTIMATE2023) AS POPESTIMATE2023
	FROM [city population].dbo.cleaned_sub_est_2014_2023
	GROUP BY NAME, STNAME
), INCIDENT_PER_STATE AS (
	SELECT GV.City_or_County AS CITY_NAME,
		GV.State_Name AS STATE_NAME,
		GV.US_Region AS REGION,
		COUNT(INCIDENT_ID)/10 AS NUM_INCIDENT
	FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023] GV
	GROUP BY GV.City_or_County, GV.State_Name, GV.US_Region
)
SELECT IPS.CITY_NAME,
		IPS.STATE_NAME,
		IPS.REGION,
		NUM_INCIDENT,
		(POPESTIMATE2014 + POPESTIMATE2015 + POPESTIMATE2016 + POPESTIMATE2017 + POPESTIMATE2018 + POPESTIMATE2019 + POPESTIMATE2020 + POPESTIMATE2021 + POPESTIMATE2022 + POPESTIMATE2023) / 10 AS AVG_POPULATION,
		CAST(NUM_INCIDENT AS FLOAT) / ((POPESTIMATE2014 + POPESTIMATE2015 + POPESTIMATE2016 + POPESTIMATE2017 + POPESTIMATE2018 + POPESTIMATE2019 + POPESTIMATE2020 + POPESTIMATE2021 + POPESTIMATE2022 + POPESTIMATE2023) / 10) * 1000 AS INCIDENT_RATE
FROM INCIDENT_PER_STATE IPS
LEFT JOIN CONSOLIDATED ON
	CONSOLIDATED.NAME = IPS.CITY_NAME AND
	CONSOLIDATED.STNAME = IPS.STATE_NAME
ORDER BY INCIDENT_RATE DESC;

/* get political leanings for each state */

WITH MOST_VOTES_PER_YEAR AS (
	SELECT DISTINCT SPL.state AS STATE,
			(SELECT TOP 1 PARTY_SIMPLIFIED FROM [state political leaning].dbo.cleaned_president_2012_2020 WHERE state = SPL.state AND year = 2012 ORDER BY candidatevotes DESC) AS '2012',
			(SELECT TOP 1 PARTY_SIMPLIFIED FROM [state political leaning].dbo.cleaned_president_2012_2020 WHERE state = SPL.state AND year = 2016 ORDER BY candidatevotes DESC) AS '2016',
			(SELECT TOP 1 PARTY_SIMPLIFIED FROM [state political leaning].dbo.cleaned_president_2012_2020 WHERE state = SPL.state AND year = 2020 ORDER BY candidatevotes DESC) AS '2020'
	FROM [state political leaning].dbo.cleaned_president_2012_2020 SPL
)
SELECT CONCAT(SUBSTRING(MVPY.STATE, 1, 1), LOWER(SUBSTRING(MVPY.STATE, 2, LEN(MVPY.STATE)))) AS STATE_NAME,
		MVPY.[2012], MVPY.[2016], MVPY.[2020],
		CASE 
			WHEN MVPY.[2012] = MVPY.[2016]  AND MVPY.[2016] = MVPY.[2020]  AND MVPY.[2020] = 'REPUBLICAN' THEN 'RED'
			WHEN MVPY.[2012] = MVPY.[2016]  AND MVPY.[2016] = MVPY.[2020]  AND MVPY.[2020] = 'DEMOCRAT' THEN 'BLUE'
			ELSE 'PURPLE'
		END AS COLOR
FROM MOST_VOTES_PER_YEAR MVPY;


/* STATE - calculating incident rate */
WITH POPULATION_AVG AS (
	SELECT NAME,
		(POPESTIMATE2014 + POPESTIMATE2015 + POPESTIMATE2016 + POPESTIMATE2017 + POPESTIMATE2018 + POPESTIMATE2019 + POPESTIMATE2020 + POPESTIMATE2021 + POPESTIMATE2022 + POPESTIMATE2023) / 10 AS AVG_POPULATION
	FROM [state population].dbo.cleaned_nst_est_2014_2023
), INCIDENT_PER_STATE AS (
	SELECT GV.State_Name AS NAME,
		GV.US_Region AS REGION,
		COUNT(INCIDENT_ID)/10 AS NUM_INCIDENT
	FROM [gun violence].dbo.[cleaned_mass_shootings_2014-2023] GV
	GROUP BY GV.State_Name, GV.US_Region
)
SELECT IPS.NAME,
		SPL.COLOR,
		IPS.REGION,
		NUM_INCIDENT,
		AVG_POPULATION,
		CAST(NUM_INCIDENT AS FLOAT) * 100000 / AVG_POPULATION AS INCIDENT_RATE
INTO DBO.incident_rates_colored
FROM INCIDENT_PER_STATE IPS
LEFT JOIN POPULATION_AVG ON
	POPULATION_AVG.NAME = IPS.NAME
LEFT JOIN [state political leaning].dbo.[state_political_color] SPL ON
	SPL.STATE_NAME = IPS.NAME
ORDER BY INCIDENT_RATE DESC;

